### ISSUE TITLE
Comments are being removed after formatting

### ISSUE THREAD

**Issue by yvssdheeraj** [gherking/gherkin-formatter#17]
## Summary
The format function is removing the comments that are previously present.

**Comment by szikszail** [comment]
@yvssdheeraj , yes this is intentional at this point.

Unfortunately, the `@cucumber/gherkin` library parses comments in such a way, that it is complicated to reverse the location of the comments after formatting and/or preprocessing with GherKing. We will assess whether it is possible to implement this feature and notify you.

**Comment by szikszail** [comment]
@yvssdheeraj support for comments is added in the latest version of gherking packages.
